I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 83, in script
    $ listaConcat = carreras[0]
  File "game/script.rpy", line 83, in <module>
    $ listaConcat = carreras[0]
IndexError: list index out of range

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 83, in script
    $ listaConcat = carreras[0]
  File "C:\Users\manue\OneDrive\Escritorio\renpy-8.2.3-sdk\renpy\ast.py", line 823, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\manue\OneDrive\Escritorio\renpy-8.2.3-sdk\renpy\python.py", line 1178, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 83, in <module>
    $ listaConcat = carreras[0]
  File "C:\Users\manue\OneDrive\Escritorio\renpy-8.2.3-sdk\renpy\revertable.py", line 221, in __getitem__
    rv = list.__getitem__(self, index)
IndexError: list index out of range

Windows-10-10.0.22621 AMD64
Ren'Py 8.2.3.24061702
Compliled Heart 1.0
Sun Jul 14 23:38:44 2024
